services:
  financial-risk-app:
    container_name: financial-risk-app
    build: .
    restart: always

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py
      - ./graph.py:/app/graph.py
      - ./ratios.py:/app/ratios.py
      - ./financial_data.py:/app/financial_data.py
